# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from articdbm import manager_pb2 as articdbm_dot_manager__pb2
from articdbm import types_pb2 as articdbm_dot_types__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in articdbm/manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagerServiceStub(object):
    """Manager service for WebUI communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDashboardStats = channel.unary_unary(
                '/articdbm.ManagerService/GetDashboardStats',
                request_serializer=articdbm_dot_manager__pb2.GetDashboardStatsRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.GetDashboardStatsResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/articdbm.ManagerService/StreamEvents',
                request_serializer=articdbm_dot_manager__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=articdbm_dot_types__pb2.Event.FromString,
                _registered_method=True)
        self.ListResources = channel.unary_unary(
                '/articdbm.ManagerService/ListResources',
                request_serializer=articdbm_dot_manager__pb2.ListResourcesRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ListResourcesResponse.FromString,
                _registered_method=True)
        self.GetResource = channel.unary_unary(
                '/articdbm.ManagerService/GetResource',
                request_serializer=articdbm_dot_manager__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.GetResourceResponse.FromString,
                _registered_method=True)
        self.CreateResource = channel.unary_unary(
                '/articdbm.ManagerService/CreateResource',
                request_serializer=articdbm_dot_manager__pb2.CreateResourceRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.CreateResourceResponse.FromString,
                _registered_method=True)
        self.UpdateResource = channel.unary_unary(
                '/articdbm.ManagerService/UpdateResource',
                request_serializer=articdbm_dot_manager__pb2.UpdateResourceRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.UpdateResourceResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/articdbm.ManagerService/DeleteResource',
                request_serializer=articdbm_dot_manager__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.DeleteResourceResponse.FromString,
                _registered_method=True)
        self.ScaleResource = channel.unary_unary(
                '/articdbm.ManagerService/ScaleResource',
                request_serializer=articdbm_dot_manager__pb2.ScaleResourceRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ScaleResourceResponse.FromString,
                _registered_method=True)
        self.GetResourceMetrics = channel.unary_unary(
                '/articdbm.ManagerService/GetResourceMetrics',
                request_serializer=articdbm_dot_manager__pb2.GetResourceMetricsRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.GetResourceMetricsResponse.FromString,
                _registered_method=True)
        self.ListApplications = channel.unary_unary(
                '/articdbm.ManagerService/ListApplications',
                request_serializer=articdbm_dot_manager__pb2.ListApplicationsRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ListApplicationsResponse.FromString,
                _registered_method=True)
        self.GetApplication = channel.unary_unary(
                '/articdbm.ManagerService/GetApplication',
                request_serializer=articdbm_dot_manager__pb2.GetApplicationRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.GetApplicationResponse.FromString,
                _registered_method=True)
        self.CreateApplication = channel.unary_unary(
                '/articdbm.ManagerService/CreateApplication',
                request_serializer=articdbm_dot_manager__pb2.CreateApplicationRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.CreateApplicationResponse.FromString,
                _registered_method=True)
        self.UpdateApplication = channel.unary_unary(
                '/articdbm.ManagerService/UpdateApplication',
                request_serializer=articdbm_dot_manager__pb2.UpdateApplicationRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.UpdateApplicationResponse.FromString,
                _registered_method=True)
        self.DeleteApplication = channel.unary_unary(
                '/articdbm.ManagerService/DeleteApplication',
                request_serializer=articdbm_dot_manager__pb2.DeleteApplicationRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.DeleteApplicationResponse.FromString,
                _registered_method=True)
        self.SyncWithElder = channel.unary_unary(
                '/articdbm.ManagerService/SyncWithElder',
                request_serializer=articdbm_dot_manager__pb2.SyncWithElderRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.SyncWithElderResponse.FromString,
                _registered_method=True)
        self.ListCredentials = channel.unary_unary(
                '/articdbm.ManagerService/ListCredentials',
                request_serializer=articdbm_dot_manager__pb2.ListCredentialsRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ListCredentialsResponse.FromString,
                _registered_method=True)
        self.GetCredential = channel.unary_unary(
                '/articdbm.ManagerService/GetCredential',
                request_serializer=articdbm_dot_manager__pb2.GetCredentialRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.GetCredentialResponse.FromString,
                _registered_method=True)
        self.CreateCredential = channel.unary_unary(
                '/articdbm.ManagerService/CreateCredential',
                request_serializer=articdbm_dot_manager__pb2.CreateCredentialRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.CreateCredentialResponse.FromString,
                _registered_method=True)
        self.RotateCredential = channel.unary_unary(
                '/articdbm.ManagerService/RotateCredential',
                request_serializer=articdbm_dot_manager__pb2.RotateCredentialRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.RotateCredentialResponse.FromString,
                _registered_method=True)
        self.ConfigureAutoRotation = channel.unary_unary(
                '/articdbm.ManagerService/ConfigureAutoRotation',
                request_serializer=articdbm_dot_manager__pb2.ConfigureAutoRotationRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ConfigureAutoRotationResponse.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/articdbm.ManagerService/DeleteCredential',
                request_serializer=articdbm_dot_manager__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.DeleteCredentialResponse.FromString,
                _registered_method=True)
        self.ListProviders = channel.unary_unary(
                '/articdbm.ManagerService/ListProviders',
                request_serializer=articdbm_dot_manager__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.GetProvider = channel.unary_unary(
                '/articdbm.ManagerService/GetProvider',
                request_serializer=articdbm_dot_manager__pb2.GetProviderRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.GetProviderResponse.FromString,
                _registered_method=True)
        self.CreateProvider = channel.unary_unary(
                '/articdbm.ManagerService/CreateProvider',
                request_serializer=articdbm_dot_manager__pb2.CreateProviderRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.CreateProviderResponse.FromString,
                _registered_method=True)
        self.UpdateProvider = channel.unary_unary(
                '/articdbm.ManagerService/UpdateProvider',
                request_serializer=articdbm_dot_manager__pb2.UpdateProviderRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.UpdateProviderResponse.FromString,
                _registered_method=True)
        self.DeleteProvider = channel.unary_unary(
                '/articdbm.ManagerService/DeleteProvider',
                request_serializer=articdbm_dot_manager__pb2.DeleteProviderRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.DeleteProviderResponse.FromString,
                _registered_method=True)
        self.TestProvider = channel.unary_unary(
                '/articdbm.ManagerService/TestProvider',
                request_serializer=articdbm_dot_manager__pb2.TestProviderRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.TestProviderResponse.FromString,
                _registered_method=True)
        self.ConfigureMarchProxy = channel.unary_unary(
                '/articdbm.ManagerService/ConfigureMarchProxy',
                request_serializer=articdbm_dot_manager__pb2.ConfigureMarchProxyRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.ConfigureMarchProxyResponse.FromString,
                _registered_method=True)
        self.RemoveMarchProxy = channel.unary_unary(
                '/articdbm.ManagerService/RemoveMarchProxy',
                request_serializer=articdbm_dot_manager__pb2.RemoveMarchProxyRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.RemoveMarchProxyResponse.FromString,
                _registered_method=True)
        self.SyncMarchProxy = channel.unary_unary(
                '/articdbm.ManagerService/SyncMarchProxy',
                request_serializer=articdbm_dot_manager__pb2.SyncMarchProxyRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.SyncMarchProxyResponse.FromString,
                _registered_method=True)
        self.AddTags = channel.unary_unary(
                '/articdbm.ManagerService/AddTags',
                request_serializer=articdbm_dot_manager__pb2.AddTagsRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.AddTagsResponse.FromString,
                _registered_method=True)
        self.RemoveTag = channel.unary_unary(
                '/articdbm.ManagerService/RemoveTag',
                request_serializer=articdbm_dot_manager__pb2.RemoveTagRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.RemoveTagResponse.FromString,
                _registered_method=True)
        self.SyncTags = channel.unary_unary(
                '/articdbm.ManagerService/SyncTags',
                request_serializer=articdbm_dot_manager__pb2.SyncTagsRequest.SerializeToString,
                response_deserializer=articdbm_dot_manager__pb2.SyncTagsResponse.FromString,
                _registered_method=True)


class ManagerServiceServicer(object):
    """Manager service for WebUI communication
    """

    def GetDashboardStats(self, request, context):
        """Dashboard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResources(self, request, context):
        """Resources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScaleResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApplications(self, request, context):
        """Applications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncWithElder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCredentials(self, request, context):
        """Credentials
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureAutoRotation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """Providers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureMarchProxy(self, request, context):
        """MarchProxy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMarchProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncMarchProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTags(self, request, context):
        """Tags
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDashboardStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDashboardStats,
                    request_deserializer=articdbm_dot_manager__pb2.GetDashboardStatsRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.GetDashboardStatsResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=articdbm_dot_manager__pb2.StreamEventsRequest.FromString,
                    response_serializer=articdbm_dot_types__pb2.Event.SerializeToString,
            ),
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=articdbm_dot_manager__pb2.ListResourcesRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ListResourcesResponse.SerializeToString,
            ),
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=articdbm_dot_manager__pb2.GetResourceRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.GetResourceResponse.SerializeToString,
            ),
            'CreateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateResource,
                    request_deserializer=articdbm_dot_manager__pb2.CreateResourceRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.CreateResourceResponse.SerializeToString,
            ),
            'UpdateResource': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResource,
                    request_deserializer=articdbm_dot_manager__pb2.UpdateResourceRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.UpdateResourceResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=articdbm_dot_manager__pb2.DeleteResourceRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.DeleteResourceResponse.SerializeToString,
            ),
            'ScaleResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ScaleResource,
                    request_deserializer=articdbm_dot_manager__pb2.ScaleResourceRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ScaleResourceResponse.SerializeToString,
            ),
            'GetResourceMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceMetrics,
                    request_deserializer=articdbm_dot_manager__pb2.GetResourceMetricsRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.GetResourceMetricsResponse.SerializeToString,
            ),
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=articdbm_dot_manager__pb2.ListApplicationsRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ListApplicationsResponse.SerializeToString,
            ),
            'GetApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApplication,
                    request_deserializer=articdbm_dot_manager__pb2.GetApplicationRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.GetApplicationResponse.SerializeToString,
            ),
            'CreateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApplication,
                    request_deserializer=articdbm_dot_manager__pb2.CreateApplicationRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.CreateApplicationResponse.SerializeToString,
            ),
            'UpdateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApplication,
                    request_deserializer=articdbm_dot_manager__pb2.UpdateApplicationRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.UpdateApplicationResponse.SerializeToString,
            ),
            'DeleteApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApplication,
                    request_deserializer=articdbm_dot_manager__pb2.DeleteApplicationRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.DeleteApplicationResponse.SerializeToString,
            ),
            'SyncWithElder': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncWithElder,
                    request_deserializer=articdbm_dot_manager__pb2.SyncWithElderRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.SyncWithElderResponse.SerializeToString,
            ),
            'ListCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCredentials,
                    request_deserializer=articdbm_dot_manager__pb2.ListCredentialsRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ListCredentialsResponse.SerializeToString,
            ),
            'GetCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredential,
                    request_deserializer=articdbm_dot_manager__pb2.GetCredentialRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.GetCredentialResponse.SerializeToString,
            ),
            'CreateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCredential,
                    request_deserializer=articdbm_dot_manager__pb2.CreateCredentialRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.CreateCredentialResponse.SerializeToString,
            ),
            'RotateCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateCredential,
                    request_deserializer=articdbm_dot_manager__pb2.RotateCredentialRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.RotateCredentialResponse.SerializeToString,
            ),
            'ConfigureAutoRotation': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureAutoRotation,
                    request_deserializer=articdbm_dot_manager__pb2.ConfigureAutoRotationRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ConfigureAutoRotationResponse.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=articdbm_dot_manager__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.DeleteCredentialResponse.SerializeToString,
            ),
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=articdbm_dot_manager__pb2.ListProvidersRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ListProvidersResponse.SerializeToString,
            ),
            'GetProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProvider,
                    request_deserializer=articdbm_dot_manager__pb2.GetProviderRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.GetProviderResponse.SerializeToString,
            ),
            'CreateProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProvider,
                    request_deserializer=articdbm_dot_manager__pb2.CreateProviderRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.CreateProviderResponse.SerializeToString,
            ),
            'UpdateProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProvider,
                    request_deserializer=articdbm_dot_manager__pb2.UpdateProviderRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.UpdateProviderResponse.SerializeToString,
            ),
            'DeleteProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProvider,
                    request_deserializer=articdbm_dot_manager__pb2.DeleteProviderRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.DeleteProviderResponse.SerializeToString,
            ),
            'TestProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.TestProvider,
                    request_deserializer=articdbm_dot_manager__pb2.TestProviderRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.TestProviderResponse.SerializeToString,
            ),
            'ConfigureMarchProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureMarchProxy,
                    request_deserializer=articdbm_dot_manager__pb2.ConfigureMarchProxyRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.ConfigureMarchProxyResponse.SerializeToString,
            ),
            'RemoveMarchProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMarchProxy,
                    request_deserializer=articdbm_dot_manager__pb2.RemoveMarchProxyRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.RemoveMarchProxyResponse.SerializeToString,
            ),
            'SyncMarchProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMarchProxy,
                    request_deserializer=articdbm_dot_manager__pb2.SyncMarchProxyRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.SyncMarchProxyResponse.SerializeToString,
            ),
            'AddTags': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTags,
                    request_deserializer=articdbm_dot_manager__pb2.AddTagsRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.AddTagsResponse.SerializeToString,
            ),
            'RemoveTag': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTag,
                    request_deserializer=articdbm_dot_manager__pb2.RemoveTagRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.RemoveTagResponse.SerializeToString,
            ),
            'SyncTags': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncTags,
                    request_deserializer=articdbm_dot_manager__pb2.SyncTagsRequest.FromString,
                    response_serializer=articdbm_dot_manager__pb2.SyncTagsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'articdbm.ManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('articdbm.ManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagerService(object):
    """Manager service for WebUI communication
    """

    @staticmethod
    def GetDashboardStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/GetDashboardStats',
            articdbm_dot_manager__pb2.GetDashboardStatsRequest.SerializeToString,
            articdbm_dot_manager__pb2.GetDashboardStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/articdbm.ManagerService/StreamEvents',
            articdbm_dot_manager__pb2.StreamEventsRequest.SerializeToString,
            articdbm_dot_types__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ListResources',
            articdbm_dot_manager__pb2.ListResourcesRequest.SerializeToString,
            articdbm_dot_manager__pb2.ListResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/GetResource',
            articdbm_dot_manager__pb2.GetResourceRequest.SerializeToString,
            articdbm_dot_manager__pb2.GetResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/CreateResource',
            articdbm_dot_manager__pb2.CreateResourceRequest.SerializeToString,
            articdbm_dot_manager__pb2.CreateResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/UpdateResource',
            articdbm_dot_manager__pb2.UpdateResourceRequest.SerializeToString,
            articdbm_dot_manager__pb2.UpdateResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/DeleteResource',
            articdbm_dot_manager__pb2.DeleteResourceRequest.SerializeToString,
            articdbm_dot_manager__pb2.DeleteResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScaleResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ScaleResource',
            articdbm_dot_manager__pb2.ScaleResourceRequest.SerializeToString,
            articdbm_dot_manager__pb2.ScaleResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/GetResourceMetrics',
            articdbm_dot_manager__pb2.GetResourceMetricsRequest.SerializeToString,
            articdbm_dot_manager__pb2.GetResourceMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ListApplications',
            articdbm_dot_manager__pb2.ListApplicationsRequest.SerializeToString,
            articdbm_dot_manager__pb2.ListApplicationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/GetApplication',
            articdbm_dot_manager__pb2.GetApplicationRequest.SerializeToString,
            articdbm_dot_manager__pb2.GetApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/CreateApplication',
            articdbm_dot_manager__pb2.CreateApplicationRequest.SerializeToString,
            articdbm_dot_manager__pb2.CreateApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/UpdateApplication',
            articdbm_dot_manager__pb2.UpdateApplicationRequest.SerializeToString,
            articdbm_dot_manager__pb2.UpdateApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/DeleteApplication',
            articdbm_dot_manager__pb2.DeleteApplicationRequest.SerializeToString,
            articdbm_dot_manager__pb2.DeleteApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncWithElder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/SyncWithElder',
            articdbm_dot_manager__pb2.SyncWithElderRequest.SerializeToString,
            articdbm_dot_manager__pb2.SyncWithElderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ListCredentials',
            articdbm_dot_manager__pb2.ListCredentialsRequest.SerializeToString,
            articdbm_dot_manager__pb2.ListCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/GetCredential',
            articdbm_dot_manager__pb2.GetCredentialRequest.SerializeToString,
            articdbm_dot_manager__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/CreateCredential',
            articdbm_dot_manager__pb2.CreateCredentialRequest.SerializeToString,
            articdbm_dot_manager__pb2.CreateCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/RotateCredential',
            articdbm_dot_manager__pb2.RotateCredentialRequest.SerializeToString,
            articdbm_dot_manager__pb2.RotateCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureAutoRotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ConfigureAutoRotation',
            articdbm_dot_manager__pb2.ConfigureAutoRotationRequest.SerializeToString,
            articdbm_dot_manager__pb2.ConfigureAutoRotationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/DeleteCredential',
            articdbm_dot_manager__pb2.DeleteCredentialRequest.SerializeToString,
            articdbm_dot_manager__pb2.DeleteCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ListProviders',
            articdbm_dot_manager__pb2.ListProvidersRequest.SerializeToString,
            articdbm_dot_manager__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/GetProvider',
            articdbm_dot_manager__pb2.GetProviderRequest.SerializeToString,
            articdbm_dot_manager__pb2.GetProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/CreateProvider',
            articdbm_dot_manager__pb2.CreateProviderRequest.SerializeToString,
            articdbm_dot_manager__pb2.CreateProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/UpdateProvider',
            articdbm_dot_manager__pb2.UpdateProviderRequest.SerializeToString,
            articdbm_dot_manager__pb2.UpdateProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/DeleteProvider',
            articdbm_dot_manager__pb2.DeleteProviderRequest.SerializeToString,
            articdbm_dot_manager__pb2.DeleteProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/TestProvider',
            articdbm_dot_manager__pb2.TestProviderRequest.SerializeToString,
            articdbm_dot_manager__pb2.TestProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureMarchProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/ConfigureMarchProxy',
            articdbm_dot_manager__pb2.ConfigureMarchProxyRequest.SerializeToString,
            articdbm_dot_manager__pb2.ConfigureMarchProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMarchProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/RemoveMarchProxy',
            articdbm_dot_manager__pb2.RemoveMarchProxyRequest.SerializeToString,
            articdbm_dot_manager__pb2.RemoveMarchProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncMarchProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/SyncMarchProxy',
            articdbm_dot_manager__pb2.SyncMarchProxyRequest.SerializeToString,
            articdbm_dot_manager__pb2.SyncMarchProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/AddTags',
            articdbm_dot_manager__pb2.AddTagsRequest.SerializeToString,
            articdbm_dot_manager__pb2.AddTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/RemoveTag',
            articdbm_dot_manager__pb2.RemoveTagRequest.SerializeToString,
            articdbm_dot_manager__pb2.RemoveTagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/articdbm.ManagerService/SyncTags',
            articdbm_dot_manager__pb2.SyncTagsRequest.SerializeToString,
            articdbm_dot_manager__pb2.SyncTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
